server:
  port: 8011

spring:
  application:
    name: drivers
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yml
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/drivers?currentSchema=drivers_schema
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

    minio:
      properties:
        url: http://${MINIO_HOST}:9000
        accessKey: ${MINIO_ACCESS_KEY}
        secretKey: ${MINIO_SECRET_KEY}
        bucketName: documents

        eureka:
          client:
            service-url:
              defaultZone: http://${EUREKA_HOST}:8761/eureka

        app:
          url: https://nominatim.openstreetmap.org/search?q=%s&format=json&polygon_kml=1&addressdetails=1

        kafka:
          port: ${KAFKA_HOST}:9092
          group: groupId
          topic: rides