server:
  port: 8011

spring:
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yml
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/drivers?currentSchema=drivers_schema
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

    minio:
      properties:
        url: http://${MINIO_HOST}:9000
        accessKey: ${MINIO_ACCESS_KEY}
        secretKey: ${MINIO_SECRET_KEY}
        bucketName: documents